/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.subway;

public final class R {
    public static final class array {
        public static final int cid_1000=0x7f040001;
        public static final int cid_1000_lid=0x7f040002;
        public static final int local=0x7f040000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int back=0x7f020000;
        public static final int delete=0x7f020001;
        public static final int exit=0x7f020002;
        public static final int forward=0x7f020003;
        public static final int ic_launcher=0x7f020004;
        public static final int icon=0x7f020005;
        public static final int info=0x7f020006;
        public static final int quit=0x7f020007;
        public static final int refresh=0x7f020008;
        public static final int subway=0x7f020009;
    }
    public static final class id {
        public static final int TextAddress=0x7f07001c;
        public static final int TextBack1=0x7f07000d;
        public static final int TextBack2=0x7f07000f;
        public static final int TextBackSchedule=0x7f070007;
        public static final int TextBackScheduleText=0x7f07000a;
        public static final int TextBackScheduleTime=0x7f070009;
        public static final int TextFirstBackSchedule=0x7f070003;
        public static final int TextFirstForSchedule=0x7f070004;
        public static final int TextFor1=0x7f07000e;
        public static final int TextFor2=0x7f070010;
        public static final int TextForSchedule=0x7f070008;
        public static final int TextForScheduleText=0x7f07000c;
        public static final int TextForScheduleTime=0x7f07000b;
        public static final int TextLastBackSchedule=0x7f070005;
        public static final int TextLastForSchedule=0x7f070006;
        public static final int TextNextStation=0x7f070001;
        public static final int TextPreStation=0x7f070000;
        public static final int TextStationName=0x7f070002;
        public static final int TextTel=0x7f07001d;
        public static final int bottomtext=0x7f070018;
        public static final int btnSearch=0x7f070017;
        public static final int exit=0x7f07001e;
        public static final int firstlasttime=0x7f070011;
        public static final int firstlasttimedetail=0x7f070012;
        public static final int firstlasttimedetail1=0x7f070013;
        public static final int firstlasttimedetail2=0x7f070014;
        public static final int linearLayout=0x7f070015;
        public static final int refrash=0x7f07001f;
        public static final int stationinfotable=0x7f07001b;
        public static final int stationinfotextview=0x7f07001a;
        public static final int toptext=0x7f070019;
        public static final int txtViewStationName=0x7f070016;
    }
    public static final class layout {
        public static final int arrivalinfo=0x7f030000;
        public static final int main=0x7f030001;
        public static final int row=0x7f030002;
        public static final int stationinfo=0x7f030003;
    }
    public static final class menu {
        public static final int menu_main=0x7f060000;
        public static final int menu_station=0x7f060001;
    }
    public static final class string {
        public static final int alert_dialog_cancle=0x7f050004;
        public static final int alert_dialog_ok=0x7f050003;
        public static final int appname=0x7f050000;
        public static final int appversion=0x7f05000f;
        public static final int delete=0x7f05000c;
        public static final int delete_item=0x7f050006;
        public static final int delete_message=0x7f05000b;
        public static final int exit=0x7f05000a;
        public static final int exit_message=0x7f050009;
        public static final int line_select=0x7f050001;
        public static final int loading=0x7f05000d;
        public static final int local_select=0x7f050002;
        public static final int menu_delete=0x7f050005;
        public static final int problem=0x7f05000e;
        public static final int sd_error=0x7f050007;
        public static final int sd_error_detail=0x7f050008;
    }
}
